name: CI/CD Pipeline

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Build and Push Docker image to ghcr
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to ghcr
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker Backend
        id: meta_backend
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/2401849/PWA_Listify

      - name: Build and push Docker Backend image
        id: push_backend
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker Frontend
        id: meta_frontend
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/2401849/PWA_Listify

      - name: Build and push Docker Frontend image
        id: push_frontend
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}